-- AFADETH Supabase backend schema.
-- Run this in Supabase SQL Editor after confirming the project URL/anon key.

create table if not exists public.albums (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  cat text not null default 'evenements',
  description text not null default '',
  cover_url text not null default '',
  date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.albums(id) on delete cascade,
  src_url text not null,
  title text not null default '',
  description text not null default '',
  is_cover boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  titre text not null,
  slug text not null unique,
  cat text not null default 'evenements',
  auteur text not null default 'AFADETH',
  cover_url text not null default '',
  resume text not null default '',
  contenu text not null default '',
  tags text[] not null default '{}',
  status text not null default 'brouillon' check (status in ('brouillon', 'publie', 'draft', 'published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  prenom text not null,
  nom text not null,
  email text not null,
  telephone text not null default '',
  sujet text not null default 'autre',
  message text not null,
  lu boolean not null default false,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  prenom text not null,
  nom text not null,
  role text not null default 'editor' check (role in ('admin', 'editor')),
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  type text not null,
  action text not null,
  user_email text not null default '',
  details text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists albums_date_idx on public.albums(date desc);
create index if not exists photos_album_sort_idx on public.photos(album_id, sort_order);
create index if not exists articles_status_published_idx on public.articles(status, published_at desc);
create index if not exists contacts_created_idx on public.contacts(created_at desc);
create index if not exists logs_created_idx on public.logs(created_at desc);

create or replace function public.is_active_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and actif is true
  );
$$;

grant usage on schema public to anon, authenticated;
grant execute on function public.is_active_admin() to authenticated;
grant select on public.albums, public.photos to anon, authenticated;
grant select on public.articles to anon, authenticated;
grant insert on public.contacts to anon, authenticated;
grant select, update, delete on public.contacts to authenticated;
grant select, insert, update, delete on public.albums, public.photos, public.articles, public.admin_users, public.logs to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter table public.albums enable row level security;
alter table public.photos enable row level security;
alter table public.articles enable row level security;
alter table public.contacts enable row level security;
alter table public.admin_users enable row level security;
alter table public.logs enable row level security;

do $$
begin
  drop policy if exists "Public can read albums" on public.albums;
  drop policy if exists "Authenticated can manage albums" on public.albums;
  drop policy if exists "Public can read photos" on public.photos;
  drop policy if exists "Authenticated can manage photos" on public.photos;
  drop policy if exists "Public can read published articles" on public.articles;
  drop policy if exists "Authenticated can manage articles" on public.articles;
  drop policy if exists "Anyone can create contacts" on public.contacts;
  drop policy if exists "Authenticated can manage contacts" on public.contacts;
  drop policy if exists "Authenticated can manage admin users" on public.admin_users;
  drop policy if exists "Active admins can manage albums" on public.albums;
  drop policy if exists "Active admins can manage photos" on public.photos;
  drop policy if exists "Active admins can manage articles" on public.articles;
  drop policy if exists "Active admins can manage contacts" on public.contacts;
  drop policy if exists "Active admins can manage admin users" on public.admin_users;
  drop policy if exists "Active admins can read logs" on public.logs;
  drop policy if exists "Active admins can create logs" on public.logs;
  drop policy if exists "Authenticated can read logs" on public.logs;
  drop policy if exists "Authenticated can create logs" on public.logs;
end $$;

create policy "Public can read albums"
on public.albums for select
to anon, authenticated
using (true);

create policy "Active admins can manage albums"
on public.albums for all
to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

create policy "Public can read photos"
on public.photos for select
to anon, authenticated
using (true);

create policy "Active admins can manage photos"
on public.photos for all
to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

create policy "Public can read published articles"
on public.articles for select
to anon, authenticated
using (status in ('publie', 'published'));

create policy "Active admins can manage articles"
on public.articles for all
to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

create policy "Anyone can create contacts"
on public.contacts for insert
to anon, authenticated
with check (true);

create policy "Active admins can manage contacts"
on public.contacts for all
to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

create policy "Active admins can manage admin users"
on public.admin_users for all
to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

create policy "Active admins can read logs"
on public.logs for select
to authenticated
using (public.is_active_admin());

create policy "Active admins can create logs"
on public.logs for insert
to authenticated
with check (public.is_active_admin());
